name: nlp-exercises
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit==11.3.1
  - cudnn==8.2.1
  - spacy==3.2.1
  - pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_releases.html
    - jax[cuda11_cudnn82]==0.3.7
    - flax==0.4.1
    - sentencepiece==0.1.96
    - gin-config==0.5.0
    - pytest==7.1.2